/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Workstation.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Workstation.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.834, 0.073, -0.514]} rotation={[0, Math.PI / 3, 0]} scale={[1.592, 2.256, 1.592]}>
        <mesh geometry={nodes.SM_027_Monstera001.geometry} material={materials.M_Monstera} scale={0.01} />
      </group>
      <group position={[0.042, -0.014, -0.054]} scale={[1.313, 0.531, 1.386]}>
        <mesh geometry={nodes.SM_ceiling3001.geometry} material={materials.M_ceiling2} scale={0.01} />
      </group>
      <group position={[0.099, 0.04, -0.629]} rotation={[0, -1.571, 0]} scale={0.531}>
        <mesh geometry={nodes.SM_desk_4_legs001.geometry} material={materials.M_desk_4_legs} scale={0.01} />
      </group>
      <group position={[-0.457, 0.816, -0.897]} scale={1.023}>
        <mesh geometry={nodes.SM_Labels001.geometry} material={materials.M_Labels} scale={0.01} />
      </group>
      <group position={[0.349, 0.498, -0.531]} scale={0.531}>
        <mesh geometry={nodes.SM_mouse_pad001.geometry} material={materials.M_mouse_pad} scale={0.01} />
      </group>
      <group position={[0.152, 0.035, -0.137]} rotation={[0, Math.PI / 9, 0]} scale={0.531}>
        <mesh geometry={nodes.SM_OfficeChair001.geometry} material={materials.M_OfficeChair} position={[-0.416, 0, -0.151]} rotation={[0, -0.548, 0]} scale={0.01} />
      </group>
      <group position={[0.435, 0.07, -0.612]} scale={0.531}>
        <mesh geometry={nodes.SM_PC_case_1001.geometry} material={materials.M_PC_case_clean} scale={0.01} />
      </group>
      <group position={[-0.25, 0.081, 0.323]} scale={0.531}>
        <mesh geometry={nodes.SM_PROXY_CAMERA_RED_FC01EADD001.geometry} material={materials.M_PROXY_CAMERA_RED_FC01EADD} position={[0.097, -0.085, 0.105]} rotation={[Math.PI, -1.276, Math.PI]} scale={0.018} />
      </group>
      <group position={[0.186, 0.493, -0.704]} scale={0.531}>
        <mesh geometry={nodes.SM_PROXY_Combined_8EE21795001.geometry} material={materials.M_PROXY_Combined_8EE21795} scale={0.01} />
      </group>
      <group position={[0.266, 0.499, -0.53]} scale={0.531}>
        <mesh geometry={nodes.SM_PROXY_MOUSE1HR_6583A33E001.geometry} material={materials.M_PROXY_MOUSE1HR_6583A33E} scale={0.01} />
      </group>
      <group position={[-0.017, 0.489, -0.517]} scale={0.531}>
        <mesh geometry={nodes.SM_PROXY_SM_keyboard_solo001.geometry} material={materials.M_PROXY_SM_keyboard_solo} scale={0.01} />
      </group>
      <group position={[-0.119, 0.865, -0.874]} scale={0.531}>
        <mesh geometry={nodes.SM_PROXY_TV_CAMERAS_PLIS_03388FC1001.geometry} material={materials.M_PROXY_TV_CAMERAS_PLIS_03388FC1} scale={0.01} />
      </group>
      <group position={[0.509, 0.493, -0.753]} rotation={[0, 1.222, 0]} scale={0.531}>
        <mesh geometry={nodes.SM_SM_snake_plant1001.geometry} material={materials.M_SM_snake_plant1} scale={0.01} />
      </group>
      <group position={[0.947, 0.034, -0.604]} rotation={[0, -0.873, 0]} scale={0.531}>
        <mesh geometry={nodes.SM_Stand_light001.geometry} material={materials.MI_Stand_light_Inst} scale={0.01} />
      </group>
      <group position={[-0.846, 0.017, 0.324]} rotation={[-Math.PI, 0.932, -Math.PI]} scale={0.531}>
        <mesh geometry={nodes.SM_Stand_light002.geometry} material={materials.MI_Stand_light_Inst} scale={0.01} />
      </group>
      <group position={[0.14, 0.049, -0.953]} rotation={[0, 1.571, 0]} scale={[0.511, 0.522, 0.431]}>
        <mesh geometry={nodes.SM_Wall001.geometry} material={materials.M_Wall2} position={[0, -0.098, 0]} scale={0.01} />
      </group>
      <group position={[-1.15, 0.007, 0.419]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.455, 0.539, 0.46]}>
        <mesh geometry={nodes.SM_windowWall1001.geometry} material={materials.M_windowWall} position={[-0.009, 0, 0]} scale={0.01} />
      </group>
      <group position={[-1.15, 0.007, -0.897]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.455, 0.539, 0.46]}>
        <mesh geometry={nodes.SM_windowWall001.geometry} material={materials.M_windowWall} scale={0.01} />
      </group>
      <group position={[1.49, 0.007, -0.946]} rotation={[0, 1.571, 0]} scale={[0.455, 0.539, 0.46]}>
        <mesh geometry={nodes.SM_windowWall2001.geometry} material={materials.M_windowWall} position={[0.014, -0.015, 0]} scale={[0.011, 0.01, 0.01]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Workstation.gltf')
